### ISSUE TITLE
Rename templates to layouts, or vice versa

### ISSUE THREAD

**Issue by NatElkins** [LambdaFactory/Fornax#12]
Right now Fornax looks at the `layout` property in the md file to find the corresponding fsx file in the templates folder.  I think that for consistency, we should either rename that property to template, or rename the templates directory to layouts.

**Comment by Krzysztof-Cieslak** [comment]
Seems reasonable, PRs welcomed

**Comment by Krzysztof-Cieslak** [comment]
Closed by #25
