### ISSUE TITLE
Cannot render tables

### ISSUE THREAD

**Issue by grishace** [LambdaFactory/Fornax#16]
https://github.com/Knagis/CommonMark.NET/issues/121
Maybe replace it with https://github.com/lunet-io/markdig ?

**Comment by grishace** [comment]
I've just tried Markdig instead of CommonMark.NET and it seems to be working.

![image](https://user-images.githubusercontent.com/8962463/62660976-d97c1c80-b92c-11e9-9dfc-aedb90ef1025.png)

Here are my changes:
https://github.com/grishace/Fornax/tree/md_package

**Comment by Neftedollar** [comment]
maybe there is a better solution to use `string -> string` function as a renderer? And the user can choose any function he needs.

**Comment by Krzysztof-Cieslak** [comment]
@grishace, looks good to me, please send PR

**Comment by WalternativE** [comment]
@Krzysztof-Cieslak @grishace this one can be closed, can't it?
