### ISSUE TITLE
Release new version on Nuget?

### ISSUE THREAD

**Issue by NatElkins** [LambdaFactory/Fornax#31]
Just reinstalled .NET SDKs on a new machine.  When I try to install Fornax as a global tool. I get the following:

```
nathaniel@nelknet-linux:~$ Fornax
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
nathaniel@nelknet-linux:~$ dotnet tool list -g
Package Id      Version      Commands
-------------------------------------
fornax          0.2.0        Fornax  
nathaniel@nelknet-linux:~$ 
```

Two things:

1. It doesn't work
2. The command requires `Fornax` to be capitalized.

Is this something that can be fixed with a new release of the global tool?

**Comment by FoggyFinder** [comment]
Vote for new release.

ReadMe contains confused information like:

> A sample website can be found in the samples folder - to build it, run fornax build in this folder.

templates were replaced by layouts so when one try to build they gets an exception.

**Comment by Krzysztof-Cieslak** [comment]
I think https://github.com/LambdaFactory/Fornax/commit/20ab9dc91734f689dca6dfa10f48ca46229d5925 should solve the problem with the capitalized name.

I'll investigate other part of the issue - I'll do new release after I figure it out (and maybe after #29 is merged if @NatElkins has some time too look at it)
