### ISSUE TITLE
Include build instructions in README

### ISSUE THREAD

**Issue by aeshthetic** [LambdaFactory/Fornax#37]
It would be nice if instructions to build the project could be easily found in the README; I don't know if they're visible elsewhere.

**Comment by aeshthetic** [comment]
Ah, I found it in the contribution document. Maybe just a note in the README specifying that build instructions could be found there would work?

**Comment by NatElkins** [comment]
You're not the only one: https://github.com/LambdaFactory/Fornax/issues/30

Go for it.
