### ISSUE TITLE
Update projects to use SDK based format

### ISSUE THREAD

**Issue by WalternativE** [LambdaFactory/Fornax#8]
# Background
I'd like to convert fornax to a dotnet cli tool because I think that the target audience would be happy to consume it this way (it also appears to be more practical to deploy it using the dotnet/nuget infrastructure). To do this there are a couple of steps I'd need to tackle:

  - Update proj format (no dotnet standard and netcore with the old proj format 🙁)
  - Use netstandard conform dependencies (FsYaml still forces full framework on the project)
  - Update build tooling to leverage dotnet sdk (not strictly necessary but if we're already touching stuff it would be an obvious target)
  - Switch to netcore (this would make sense in the mentioned scenario - it is debatable though)

Does this sound like a good idea - would you wish to see the project go in another direction?

# WIP
I created a pull request which implements the needed changes to use the new project formats. I'd open other issues to address the other topics in a more focused manner. The PR is #7.

**Comment by Krzysztof-Cieslak** [comment]
In general I'd love to make it (global?) `dotnet` CLI tool.... but there is one more problem - Fornax is using F# Interactive part of the FSharp.Compiler.Services... and I think it's not supported on .Net Core.

**Comment by WalternativE** [comment]
I see. That is problem I wasn't aware of. I'd still try to tackle all other described issues. Eventually FSharp Interactive will become available on .Net Core if everything else is ready and in place it shouldn't be to hard to get the cli tool ready.

The next things I'd like to work on would be the move away from FsYaml (don't have anything against the project but it forces the full framework on fornax - also I'm absolutely incapable of speaking and/or understanding Japanese, which makes all the documentation which exists on the project unintelligibel to me) as well as changes to the `build.fsx` (maybe building on the changes from #4 - switching to `dotnet` tooling etc).

Would that be in your interest or do you see more high priority targets?

**Comment by Krzysztof-Cieslak** [comment]
Both those suggestions seems fine for me. :-)

**Comment by WalternativE** [comment]
I managed to swap out FsYaml with the corresponding functionality in YamlDotNet. As far as I can tell it shouldn't break existing interfaces. There is one catch though - the models used in the pages have to be annotated with the `[<CLIMutable>]` attribute.

This is necessary because of the usage of the `Deserializer` class.
```fsharp
    let parse (modelType : Type) (document : string) =
        let deserializer =
            DeserializerBuilder()
                .IgnoreUnmatchedProperties()
                .Build()
        let method = (typedefof<Deserializer>).GetMethod("Deserialize", [| typedefof<string> |])
        let genericMethod = method.MakeGenericMethod(modelType)
        genericMethod.Invoke(deserializer, [| document |]) 
```
Is this acceptable or should I try to find a better way? I already played around with FsYaml source code and I think I should understand it well enough to replicate its reading/parsing functionality for this use case. What do you think. My current WIP can be found here https://github.com/WalternativE/Fornax/tree/change-yaml-dep .

**Comment by Krzysztof-Cieslak** [comment]
This has been done in #11
